#ifndef ACTIVEBUSCORE_GLOBAL_H
#define ACTIVEBUSCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ACTIVEBUSCORE_LIBRARY)
#  define ACTIVEBUSCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ACTIVEBUSCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ACTIVEBUSCORE_GLOBAL_H
